In [42]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [3]:
list_data = [1,2,3,4,5]

In [4]:
np.array(list_data) #hanya bisa untuk tipe data yang sama

array([1, 2, 3, 4, 5])

In [5]:
multidimensional_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
multidimensional_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
multidimensional_array.shape

(3, 3)

In [8]:
multidimensional_array.dtype

dtype('int64')

int16, int32, dan int64 itu beda. bedanya ada di maksimal nominal angka

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,7) #10 dibagi dengan 7 sama rata

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [23]:
multidimensional_array[2][2]

np.int64(9)

In [24]:
my_array = np.linspace(0,10, 50)

In [26]:
pd_series = pd.Series(my_array)
pd_series

0      0.000000
1      0.204082
2      0.408163
3      0.612245
4      0.816327
5      1.020408
6      1.224490
7      1.428571
8      1.632653
9      1.836735
10     2.040816
11     2.244898
12     2.448980
13     2.653061
14     2.857143
15     3.061224
16     3.265306
17     3.469388
18     3.673469
19     3.877551
20     4.081633
21     4.285714
22     4.489796
23     4.693878
24     4.897959
25     5.102041
26     5.306122
27     5.510204
28     5.714286
29     5.918367
30     6.122449
31     6.326531
32     6.530612
33     6.734694
34     6.938776
35     7.142857
36     7.346939
37     7.551020
38     7.755102
39     7.959184
40     8.163265
41     8.367347
42     8.571429
43     8.775510
44     8.979592
45     9.183673
46     9.387755
47     9.591837
48     9.795918
49    10.000000
dtype: float64

In [ ]:
#inimah nice to know aja
series_custom_label = pd.Series(list_data, index=['a','b','c','d','e'])
series_custom_label

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [30]:
#inimah nice to know aja
series_custom_label2 = pd.Series(list_data, index=['x','z','c','b','a',])
series_custom_label2

x    1
z    2
c    3
b    4
a    5
dtype: int64

In [31]:
series_custom_label + series_custom_label2

a    6.0
b    6.0
c    6.0
d    NaN
e    NaN
x    NaN
z    NaN
dtype: float64

In [ ]:
#index dikasih label lebih sering digunakan di dataframe, biasanya buat data time series
#jadi indexnya berupa tanggal, bisa di slicing based on tanggal juga
pd.DataFrame({'Kolom 1':series_custom_label, 'Kolom 2':series_custom_label2})

Kolom 1  Kolom 2
a      1.0      5.0
b      2.0      4.0
c      3.0      3.0
d      4.0      NaN
e      5.0      NaN
x      NaN      1.0
z      NaN      2.0

In [33]:
a = [i for i in range(1,5)]
b = [i for i in range(5,9)]
c = [i for i in range(9,13)]

In [39]:
pd.DataFrame(data=[a,b,c], columns='w x y z'.split(), index=['a','b','c'])

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [40]:
list(zip(a,b,c))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

pembuatan dataframe dari dictionary, otomatis key nya akan menjadi kolom

In [43]:
taxi_data = pd.read_csv('Session9_sample_taxi_data.csv')

In [51]:
taxi_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   vendor_id            10000 non-null  int64  
 1   pickup_datetime      10000 non-null  object 
 2   dropoff_datetime     10000 non-null  object 
 3   passenger_count      10000 non-null  int64  
 4   trip_distance        10000 non-null  float64
 5   rate_code            10000 non-null  int64  
 6   store_and_fwd_flag   10000 non-null  object 
 7   payment_type         10000 non-null  int64  
 8   fare_amount          10000 non-null  float64
 9   extra                10000 non-null  float64
 10  mta_tax              10000 non-null  float64
 11  tip_amount           10000 non-null  float64
 12  tolls_amount         10000 non-null  float64
 13  imp_surcharge        10000 non-null  float64
 14  total_amount         10000 non-null  float64
 15  pickup_location_id   10000 non-null  

In [55]:
taxi_data.describe(include=object)

pickup_datetime     dropoff_datetime store_and_fwd_flag
count                 10000                10000              10000
unique                 4627                 4393                  2
top     2018-12-31T23:18:39  2019-01-01T00:00:00                  N
freq                     10                   65               9967

In [56]:
taxi_data.describe()

vendor_id  passenger_count  trip_distance    rate_code  \
count  10000.000000     10000.000000   10000.000000  10000.00000   
mean       1.688100         1.717900       3.645685      1.06950   
std        0.543183         1.299034       4.672777      1.05441   
min        1.000000         0.000000       0.000000      1.00000   
25%        1.000000         1.000000       0.970000      1.00000   
50%        2.000000         1.000000       1.880000      1.00000   
75%        2.000000         2.000000       4.200000      1.00000   
max        4.000000         6.000000      83.050000     99.00000   

       payment_type   fare_amount         extra       mta_tax    tip_amount  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       1.444100     14.014530      0.480800      0.495550      1.759091   
std        0.529059     14.028679      0.196304      0.056617      3.233006   
min        1.000000   -260.000000     -0.500000     -0.500000      0.000000   
25%        1.000000      6.000000      0.500000      0.500000      0.000000   
50%        1.000000      9.500000      0.500000      0.500000      1.000000   
75%        2.000000     16.500000      0.500000      0.500000      2.260000   
max        4.000000    260.000000      4.500000      0.500000    110.230000   

       tolls_amount  imp_surcharge  total_amount  pickup_location_id  \
count  10000.000000   10000.000000  10000.000000        10000.000000   
mean       0.334228       0.298590     17.390214          156.946100   
std        1.763243       0.028268     16.480363           67.572673   
min        0.000000      -0.300000   -260.300000            4.000000   
25%        0.000000       0.300000      8.300000          113.000000   
50%        0.000000       0.300000     11.800000          148.000000   
75%        0.000000       0.300000     19.800000          231.000000   
max      100.500000       0.300000    260.300000          265.000000   

       dropoff_location_id  
count         10000.000000  
mean            154.222700  
std              75.388397  
min               1.000000  
25%              82.000000  
50%             153.000000  
75%             234.000000  
max             265.000000

In [60]:
taxi_data[taxi_data['fare_amount'] == -260]

vendor_id      pickup_datetime     dropoff_datetime  passenger_count  \
44          2  2018-12-31T23:19:32  2018-12-31T23:33:52                3   

    trip_distance  rate_code store_and_fwd_flag  payment_type  fare_amount  \
44            0.0          5                  N             3       -260.0   

    extra  mta_tax  tip_amount  tolls_amount  imp_surcharge  total_amount  \
44    0.0      0.0         0.0           0.0           -0.3        -260.3   

    pickup_location_id  dropoff_location_id  
44                 265                  265

In [63]:
taxi_data['passenger_count'].value_counts()

passenger_count
1    6396
2    1810
3     584
5     529
4     291
6     267
0     123
Name: count, dtype: int64

In [71]:
df = pd.DataFrame(
    {'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]}
)

In [ ]:
df

In [72]:
df.dropna() #hapus row yang ada null nya

A    B  C
0  1.0  5.0  1

In [73]:
df.dropna(axis=1) #hapus kolom yang ada nullnya

C
0  1
1  2
2  3

In [74]:
df.dropna(thresh=2) #minimal ada 2 value yang non null di tiap baris

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [75]:
df.dropna(axis=1,thresh=2)

A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [76]:
df.dropna(subset=['A']) #hapus baris kalo di kolom a ada null value

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [77]:
df.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [80]:
taxi_data.groupby('vendor_id').count()

pickup_datetime  dropoff_datetime  passenger_count  trip_distance  \
vendor_id                                                                      
1                     3387              3387             3387           3387   
2                     6479              6479             6479           6479   
4                      134               134              134            134   

           rate_code  store_and_fwd_flag  payment_type  fare_amount  extra  \
vendor_id                                                                    
1               3387                3387          3387         3387   3387   
2               6479                6479          6479         6479   6479   
4                134                 134           134          134    134   

           mta_tax  tip_amount  tolls_amount  imp_surcharge  total_amount  \
vendor_id                                                                   
1             3387        3387          3387           3387          3387   
2             6479        6479          6479           6479          6479   
4              134         134           134            134           134   

           pickup_location_id  dropoff_location_id  
vendor_id                                           
1                        3387                 3387  
2                        6479                 6479  
4                         134                  134

In [83]:
taxi_data.groupby('vendor_id').median(numeric_only=True)

passenger_count  trip_distance  rate_code  payment_type  \
vendor_id                                                            
1                      1.0          1.800        1.0           1.0   
2                      1.0          1.940        1.0           1.0   
4                      1.0          1.505        1.0           1.0   

           fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
vendor_id                                                          
1                  9.0    0.5      0.5        1.00           0.0   
2                  9.5    0.5      0.5        1.00           0.0   
4                  8.0    0.5      0.5        0.86           0.0   

           imp_surcharge  total_amount  pickup_location_id  \
vendor_id                                                    
1                    0.3         11.75               148.0   
2                    0.3         12.30               148.0   
4                    0.3         10.38               143.0   

           dropoff_location_id  
vendor_id                       
1                        158.0  
2                        152.0  
4                        159.5

In [86]:
taxi_data[['vendor_id', 'trip_distance']].groupby('vendor_id').mean()

trip_distance
vendor_id               
1               3.533894
2               3.706912
4               3.510970

In [87]:
df.loc[3] = [3,4,5]

In [97]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3
3  3.0  4.0  5

In [98]:
df['B']

0    5.0
1    NaN
2    NaN
3    4.0
Name: B, dtype: float64

In [96]:
df.loc[2]

A    NaN
B    NaN
C    3.0
Name: 2, dtype: float64

In [103]:
taxi_data.sort_values('vendor_id', ascending=False).reset_index(drop=True).head()

vendor_id      pickup_datetime     dropoff_datetime  passenger_count  \
0          4  2018-12-31T23:41:04  2018-12-31T23:56:35                1   
1          4  2018-12-31T23:25:16  2018-12-31T23:36:43                1   
2          4  2018-12-31T23:05:03  2018-12-31T23:09:57                4   
3          4  2018-12-31T23:43:01  2019-01-01T00:16:29                1   
4          4  2018-12-31T23:30:31  2018-12-31T23:37:00                2   

   trip_distance  rate_code store_and_fwd_flag  payment_type  fare_amount  \
0           6.57          4                  N             1         22.5   
1           5.11          4                  N             1         17.5   
2           0.51          1                  N             2          5.0   
3           9.68          1                  N             1         33.5   
4           1.33          1                  N             2          7.0   

   extra  mta_tax  tip_amount  tolls_amount  imp_surcharge  total_amount  \
0    0.5      0.5        4.76          0.00            0.3         28.56   
1    0.5      0.5        3.76          0.00            0.3         22.56   
2    0.5      0.5        0.00          0.00            0.3          6.30   
3    0.5      0.5        8.11          5.76            0.3         48.67   
4    0.5      0.5        0.00          0.00            0.3          8.30   

   pickup_location_id  dropoff_location_id  
0                 132                  265  
1                 132                  265  
2                 229                  161  
3                 138                  246  
4                 161                  137

In [105]:
taxi_data.sort_values(['vendor_id','passenger_count'], ascending=[True,False]).reset_index(drop=True).head()

vendor_id      pickup_datetime     dropoff_datetime  passenger_count  \
0          1  2018-12-31T23:39:21  2018-12-31T23:48:50                6   
1          1  2018-12-31T23:14:01  2018-12-31T23:38:55                6   
2          1  2018-12-31T23:30:01  2018-12-31T23:44:32                6   
3          1  2018-12-31T23:49:01  2018-12-31T23:52:48                5   
4          1  2018-12-31T23:04:56  2018-12-31T23:15:27                5   

   trip_distance  rate_code store_and_fwd_flag  payment_type  fare_amount  \
0            1.3          1                  N             1          8.0   
1            3.8          1                  N             1         17.0   
2            3.0          1                  N             2         12.0   
3            0.7          1                  N             1          5.0   
4            1.1          1                  N             2          8.0   

   extra  mta_tax  tip_amount  tolls_amount  imp_surcharge  total_amount  \
0    0.5      0.5        1.85           0.0            0.3         11.15   
1    0.5      0.5        0.50           0.0            0.3         18.80   
2    0.5      0.5        0.00           0.0            0.3         13.30   
3    0.5      0.5        1.25           0.0            0.3          7.55   
4    0.5      0.5        0.00           0.0            0.3          9.30   

   pickup_location_id  dropoff_location_id  
0                 158                  144  
1                 164                  238  
2                 170                  143  
3                 137                  137  
4                 162                  170

In [108]:
df.iloc[2]

A    NaN
B    NaN
C    3.0
Name: 2, dtype: float64

In [111]:
df_name = pd.read_csv('Session9_fake_data.csv')

In [117]:
df_name['first_name'].str.upper()

0        JOSH
1         MAX
2      VERNEY
3      FRASCO
4      TIMMIE
        ...  
995     MELLI
996     MINNY
997     LOTTA
998     BUFFY
999    AGNESE
Name: first_name, Length: 1000, dtype: object

In [122]:
df_name['first_name'].str[0:2]

0      Jo
1      Ma
2      Ve
3      Fr
4      Ti
       ..
995    Me
996    Mi
997    Lo
998    Bu
999    Ag
Name: first_name, Length: 1000, dtype: object

In [125]:
orders = pd.read_csv('Session9_raw_orders.csv')
customer = pd.read_csv('Session9_raw_customers.csv')

In [133]:
orders.head()

id                              customer  \
0  9bed808a-5074-4dfb-b1eb-388e2e60a6da  50a2d1c4-d788-4498-a6f7-dd75d4db588f   
1  b83630c1-0fdc-4cd2-818d-0b6d4384ce86  438005c2-dd1d-48aa-8bfd-7fb06851b5f8   
2  3b4a03db-7b23-4673-a88a-7f51b01ca497  5261268c-aa94-438a-921a-05efc0d414ac   
3  3368b213-6687-4338-bf73-b927ae72340f  f8486fce-bc07-4a4f-a6e9-ed6a06ba996c   
4  739bf2f3-8d20-4159-9124-5451f1e4b136  341ed9b2-1760-4720-a1b1-42681d273c63   

            ordered_at                              store_id  subtotal  \
0  2016-09-01T15:01:00  4b6c2304-2b9e-41e4-942a-cf11a1819378       700   
1  2016-09-01T10:39:00  4b6c2304-2b9e-41e4-942a-cf11a1819378       700   
2  2016-09-01T07:46:00  4b6c2304-2b9e-41e4-942a-cf11a1819378       700   
3  2016-09-01T14:39:00  4b6c2304-2b9e-41e4-942a-cf11a1819378       600   
4  2016-09-01T10:57:00  4b6c2304-2b9e-41e4-942a-cf11a1819378      1100   

   tax_paid  order_total  
0        42          742  
1        42          742  
2        42          742  
3        36          636  
4        65         1165

In [131]:
customer.head()

id            name
0  50a2d1c4-d788-4498-a6f7-dd75d4db588f  Stephanie Love
1  438005c2-dd1d-48aa-8bfd-7fb06851b5f8   Kristi Keller
2  5261268c-aa94-438a-921a-05efc0d414ac  Allison Oliver
3  f8486fce-bc07-4a4f-a6e9-ed6a06ba996c    Nancy Austin
4  341ed9b2-1760-4720-a1b1-42681d273c63    Christy Rios

In [134]:
pd.merge(orders,customer, left_on='customer', right_on = 'id', how='inner')

id_x  \
0      9bed808a-5074-4dfb-b1eb-388e2e60a6da   
1      b83630c1-0fdc-4cd2-818d-0b6d4384ce86   
2      3b4a03db-7b23-4673-a88a-7f51b01ca497   
3      3368b213-6687-4338-bf73-b927ae72340f   
4      739bf2f3-8d20-4159-9124-5451f1e4b136   
...                                     ...   
61943  d655d186-275f-4411-9a23-2f6d68f97578   
61944  f6d1a004-6d02-4846-974c-aa48891cf1e1   
61945  505da4ed-218d-47ce-bb62-caadac5da974   
61946  1b41551c-b925-4cf5-820f-b014a23015a0   
61947  2cf79940-d9ca-4d16-a1f2-d0d36ac929b1   

                                   customer           ordered_at  \
0      50a2d1c4-d788-4498-a6f7-dd75d4db588f  2016-09-01T15:01:00   
1      438005c2-dd1d-48aa-8bfd-7fb06851b5f8  2016-09-01T10:39:00   
2      5261268c-aa94-438a-921a-05efc0d414ac  2016-09-01T07:46:00   
3      f8486fce-bc07-4a4f-a6e9-ed6a06ba996c  2016-09-01T14:39:00   
4      341ed9b2-1760-4720-a1b1-42681d273c63  2016-09-01T10:57:00   
...                                     ...                  ...   
61943  2d4e6ed6-f081-4049-b92a-7792dbe97b89  2017-08-31T11:31:00   
61944  3d6f18db-a49c-4563-9445-68d4e02bd664  2017-08-31T08:14:00   
61945  e8014144-a99b-4ca2-8418-56404aee2f08  2017-08-31T16:07:00   
61946  8f054a96-7920-42dc-b286-f6980ea8dbeb  2017-08-31T17:41:00   
61947  9f72b282-1f70-450b-988f-9b3029fa121e  2017-08-31T08:07:00   

                                   store_id  subtotal  tax_paid  order_total  \
0      4b6c2304-2b9e-41e4-942a-cf11a1819378       700        42          742   
1      4b6c2304-2b9e-41e4-942a-cf11a1819378       700        42          742   
2      4b6c2304-2b9e-41e4-942a-cf11a1819378       700        42          742   
3      4b6c2304-2b9e-41e4-942a-cf11a1819378       600        36          636   
4      4b6c2304-2b9e-41e4-942a-cf11a1819378      1100        65         1165   
...                                     ...       ...       ...          ...   
61943  40e6ddd6-b8f6-4e17-8bd6-5e53966809d2       600        24          624   
61944  40e6ddd6-b8f6-4e17-8bd6-5e53966809d2       600        24          624   
61945  40e6ddd6-b8f6-4e17-8bd6-5e53966809d2       600        24          624   
61946  40e6ddd6-b8f6-4e17-8bd6-5e53966809d2      1200        48         1248   
61947  40e6ddd6-b8f6-4e17-8bd6-5e53966809d2       600        24          624   

                                       id_y            name  
0      50a2d1c4-d788-4498-a6f7-dd75d4db588f  Stephanie Love  
1      438005c2-dd1d-48aa-8bfd-7fb06851b5f8   Kristi Keller  
2      5261268c-aa94-438a-921a-05efc0d414ac  Allison Oliver  
3      f8486fce-bc07-4a4f-a6e9-ed6a06ba996c    Nancy Austin  
4      341ed9b2-1760-4720-a1b1-42681d273c63    Christy Rios  
...                                     ...             ...  
61943  2d4e6ed6-f081-4049-b92a-7792dbe97b89    Derek Hunter  
61944  3d6f18db-a49c-4563-9445-68d4e02bd664  David Thompson  
61945  e8014144-a99b-4ca2-8418-56404aee2f08  Michael Flores  
61946  8f054a96-7920-42dc-b286-f6980ea8dbeb    Don Valencia  
61947  9f72b282-1f70-450b-988f-9b3029fa121e  Christina Hall  

[61948 rows x 9 columns]